<?php

declare(strict_types=1);

namespace App\Enum;

class Countries
{
    public const GOOGLE_COUNTRIES = [
        [
            'key' => 'ET',
            'name_ar' => 'إثيوبيا ',
            'name_native' => 'Ethiopia',
        ],
        [
            'key' => 'AZ',
            'name_ar' => 'أذربيجان ',
            'name_native' => 'Azərbaycan',
        ],
        [
            'key' => 'AM',
            'name_ar' => 'أرمينيا ',
            'name_native' => 'Հայաստան',
        ],
        [
            'key' => 'AW',
            'name_ar' => 'أروبا ',
            'name_native' => 'Aruba',
        ],
        [
            'key' => 'ER',
            'name_ar' => 'إريتريا ',
            'name_native' => 'ኤርትራ',
        ],
        [
            'key' => 'ES',
            'name_ar' => 'إسبانيا ',
            'name_native' => 'España',
        ],
        [
            'key' => 'AU',
            'name_ar' => 'أستراليا ',
            'name_native' => 'Australia',
        ],
        [
            'key' => 'EE',
            'name_ar' => 'إستونيا ',
            'name_native' => 'Eesti',
        ],
        [
            'key' => 'IL',
            'name_ar' => 'إسرائيل ',
            'name_native' => 'ישראל',
        ],
        [
            'key' => 'SZ',
            'name_ar' => 'إسواتيني ',
            'name_native' => 'Eswatini',
        ],
        [
            'key' => 'AF',
            'name_ar' => 'أفغانستان ',
            'name_native' => 'افغانستان',
        ],
        [
            'key' => 'AL',
            'name_ar' => 'ألبانيا ',
            'name_native' => 'Shqipëri',
        ],
        [
            'key' => 'DE',
            'name_ar' => 'ألمانيا ',
            'name_native' => 'Deutschland',
        ],
        [
            'key' => 'AQ',
            'name_ar' => 'أنتاركتيكا ',
            'name_native' => 'Antarctica',
        ],
        [
            'key' => 'AG',
            'name_ar' => 'أنتيغوا وبربودا ',
            'name_native' => 'Antigua & Barbuda',
        ],
        [
            'key' => 'AD',
            'name_ar' => 'أندورا ',
            'name_native' => 'Andorra',
        ],
        [
            'key' => 'ID',
            'name_ar' => 'إندونيسيا ',
            'name_native' => 'Indonesia',
        ],
        [
            'key' => 'AO',
            'name_ar' => 'أنغولا ',
            'name_native' => 'Angola',
        ],
        [
            'key' => 'AI',
            'name_ar' => 'أنغويلا ',
            'name_native' => 'Anguilla',
        ],
        [
            'key' => 'UY',
            'name_ar' => 'أورغواي ',
            'name_native' => 'Uruguay',
        ],
        [
            'key' => 'UZ',
            'name_ar' => 'أوزبكستان ',
            'name_native' => 'Oʻzbekiston',
        ],
        [
            'key' => 'UG',
            'name_ar' => 'أوغندا ',
            'name_native' => 'Uganda',
        ],
        [
            'key' => 'UA',
            'name_ar' => 'أوكرانيا ',
            'name_native' => 'Україна',
        ],
        [
            'key' => 'IR',
            'name_ar' => 'إيران ',
            'name_native' => 'ایران',
        ],
        [
            'key' => 'IE',
            'name_ar' => 'أيرلندا ',
            'name_native' => 'Ireland',
        ],
        [
            'key' => 'IS',
            'name_ar' => 'آيسلندا ',
            'name_native' => 'Ísland',
        ],
        [
            'key' => 'IT',
            'name_ar' => 'إيطاليا ',
            'name_native' => 'Italia',
        ],
        [
            'key' => 'AR',
            'name_ar' => 'الأرجنتين ',
            'name_native' => 'Argentina',
        ],
        [
            'key' => 'JO',
            'name_ar' => 'الأردن',
        ],
        [
            'key' => 'TF',
            'name_ar' => 'الأقاليم الجنوبية الفرنسية ',
            'name_native' => 'Terres australes françaises',
        ],
        [
            'key' => 'IO',
            'name_ar' => 'الإقليم البريطاني في المحيط الهندي ',
            'name_native' => 'British Indian Ocean Territory',
        ],
        [
            'key' => 'EC',
            'name_ar' => 'الإكوادور ',
            'name_native' => 'Ecuador',
        ],
        [
            'key' => 'AE',
            'name_ar' => 'الإمارات العربية المتحدة       ',
        ],
        [
            'key' => 'BH',
            'name_ar' => 'البحرين       ',
        ],
        [
            'key' => 'BR',
            'name_ar' => 'البرازيل ',
            'name_native' => 'Brasil',
        ],
        [
            'key' => 'PT',
            'name_ar' => 'البرتغال ',
            'name_native' => 'Portugal',
        ],
        [
            'key' => 'BA',
            'name_ar' => 'البوسنة والهرسك ',
            'name_native' => 'Bosna i Hercegovina',
        ],
        [
            'key' => 'CZ',
            'name_ar' => 'التشيك ',
            'name_native' => 'Česko',
        ],
        [
            'key' => 'ME',
            'name_ar' => 'الجبل الأسود ',
            'name_native' => 'Crna Gora',
        ],
        [
            'key' => 'DZ',
            'name_ar' => 'الجزائر ',
            'name_native' => 'Algeria',
        ],
        [
            'key' => 'DK',
            'name_ar' => 'الدانمرك ',
            'name_native' => 'Danmark',
        ],
        [
            'key' => 'CV',
            'name_ar' => 'الرأس الأخضر ',
            'name_native' => 'Kabu Verdi',
        ],
        [
            'key' => 'SV',
            'name_ar' => 'السلفادور ',
            'name_native' => 'El Salvador',
        ],
        [
            'key' => 'SN',
            'name_ar' => 'السنغال ',
            'name_native' => 'Senegaal',
        ],
        [
            'key' => 'SD',
            'name_ar' => 'السودان       ',
        ],
        [
            'key' => 'SE',
            'name_ar' => 'السويد ',
            'name_native' => 'Sverige',
        ],
        [
            'key' => 'EH',
            'name_ar' => 'الصحراء الغربية       ',
        ],
        [
            'key' => 'SO',
            'name_ar' => 'الصومال ',
            'name_native' => 'Soomaaliya',
        ],
        [
            'key' => 'CN',
            'name_ar' => 'الصين ',
            'name_native' => '中国',
        ],
        [
            'key' => 'IQ',
            'name_ar' => 'العراق      ',
        ],
        [
            'key' => 'GA',
            'name_ar' => 'الغابون ',
            'name_native' => 'Gabon',
        ],
        [
            'key' => 'VA',
            'name_ar' => 'الفاتيكان ',
            'name_native' => 'Città del Vaticano',
        ],
        [
            'key' => 'PH',
            'name_ar' => 'الفلبين ',
            'name_native' => 'Philippines',
        ],
        [
            'key' => 'CM',
            'name_ar' => 'الكاميرون ',
            'name_native' => 'Cameroun',
        ],
        [
            'key' => 'CG',
            'name_ar' => 'الكونغو - برازافيل ',
            'name_native' => 'Congo-Brazzaville',
        ],
        [
            'key' => 'CD',
            'name_ar' => 'الكونغو - كينشاسا ',
            'name_native' => 'Jamhuri ya Kidemokrasia ya Kongo',
        ],
        [
            'key' => 'KW',
            'name_ar' => 'الكويت      ',
        ],
        [
            'key' => 'MA',
            'name_ar' => 'المغرب ',
            'name_native' => 'Morocco',
        ],
        [
            'key' => 'MX',
            'name_ar' => 'المكسيك ',
            'name_native' => 'México',
        ],
        [
            'key' => 'SA',
            'name_ar' => 'المملكة العربية السعودية        ',
        ],
        [
            'key' => 'GB',
            'name_ar' => 'المملكة المتحدة ',
            'name_native' => 'United Kingdom',
        ],
        [
            'key' => 'NO',
            'name_ar' => 'النرويج ',
            'name_native' => 'Norge',
        ],
        [
            'key' => 'AT',
            'name_ar' => 'النمسا ',
            'name_native' => 'Österreich',
        ],
        [
            'key' => 'NE',
            'name_ar' => 'النيجر ',
            'name_native' => 'Nijar',
        ],
        [
            'key' => 'IN',
            'name_ar' => 'الهند ',
            'name_native' => 'भारत',
        ],
        [
            'key' => 'US',
            'name_ar' => 'الولايات المتحدة ',
            'name_native' => 'United States',
        ],
        [
            'key' => 'JP',
            'name_ar' => 'اليابان ',
            'name_native' => '日本',
        ],
        [
            'key' => 'YE',
            'name_ar' => 'اليمن     ',
        ],
        [
            'key' => 'GR',
            'name_ar' => 'اليونان ',
            'name_native' => 'Ελλάδα',
        ],
        [
            'key' => 'PG',
            'name_ar' => 'بابوا غينيا الجديدة ',
            'name_native' => 'Papua New Guinea',
        ],
        [
            'key' => 'PY',
            'name_ar' => 'باراغواي ',
            'name_native' => 'Paraguay',
        ],
        [
            'key' => 'PK',
            'name_ar' => 'باكستان ',
            'name_native' => 'پاکستان',
        ],
        [
            'key' => 'PW',
            'name_ar' => 'بالاو ',
            'name_native' => 'Palau',
        ],
        [
            'key' => 'BB',
            'name_ar' => 'بربادوس ',
            'name_native' => 'Barbados',
        ],
        [
            'key' => 'BM',
            'name_ar' => 'برمودا ',
            'name_native' => 'Bermuda',
        ],
        [
            'key' => 'BN',
            'name_ar' => 'بروناي ',
            'name_native' => 'Brunei',
        ],
        [
            'key' => 'BE',
            'name_ar' => 'بلجيكا ',
            'name_native' => 'Belgium',
        ],
        [
            'key' => 'BG',
            'name_ar' => 'بلغاريا ',
            'name_native' => 'България',
        ],
        [
            'key' => 'BZ',
            'name_ar' => 'بليز ',
            'name_native' => 'Belize',
        ],
        [
            'key' => 'BD',
            'name_ar' => 'بنغلاديش ',
            'name_native' => 'বাংলাদেশ',
        ],
        [
            'key' => 'PA',
            'name_ar' => 'بنما ',
            'name_native' => 'Panamá',
        ],
        [
            'key' => 'BJ',
            'name_ar' => 'بنين ',
            'name_native' => 'Bénin',
        ],
        [
            'key' => 'BT',
            'name_ar' => 'بوتان ',
            'name_native' => 'འབྲུག',
        ],
        [
            'key' => 'BW',
            'name_ar' => 'بوتسوانا ',
            'name_native' => 'Botswana',
        ],
        [
            'key' => 'PR',
            'name_ar' => 'بورتوريكو ',
            'name_native' => 'Puerto Rico',
        ],
        [
            'key' => 'BF',
            'name_ar' => 'بوركينا فاسو ',
            'name_native' => 'Burkina Faso',
        ],
        [
            'key' => 'BI',
            'name_ar' => 'بوروندي ',
            'name_native' => 'Uburundi',
        ],
        [
            'key' => 'PL',
            'name_ar' => 'بولندا ',
            'name_native' => 'Polska',
        ],
        [
            'key' => 'BO',
            'name_ar' => 'بوليفيا ',
            'name_native' => 'Bolivia',
        ],
        [
            'key' => 'PF',
            'name_ar' => 'بولينيزيا الفرنسية ',
            'name_native' => 'Polynésie française',
        ],
        [
            'key' => 'PE',
            'name_ar' => 'بيرو ',
            'name_native' => 'Perú',
        ],
        [
            'key' => 'BY',
            'name_ar' => 'بيلاروس ',
            'name_native' => 'Беларусь',
        ],
        [
            'key' => 'TH',
            'name_ar' => 'تايلاند ',
            'name_native' => 'ไทย',
        ],
        [
            'key' => 'TW',
            'name_ar' => 'تايوان ',
            'name_native' => '台灣',
        ],
        [
            'key' => 'TM',
            'name_ar' => 'تركمانستان ',
            'name_native' => 'Türkmenistan',
        ],
        [
            'key' => 'TR',
            'name_ar' => 'تركيا ',
            'name_native' => 'Türkiye',
        ],
        [
            'key' => 'TA',
            'name_ar' => 'تريستان دا كونا ',
            'name_native' => 'Tristan da Cunha',
        ],
        [
            'key' => 'TT',
            'name_ar' => 'ترينيداد وتوباغو ',
            'name_native' => 'Trinidad & Tobago',
        ],
        [
            'key' => 'TD',
            'name_ar' => 'تشاد ',
            'name_native' => 'Tchad',
        ],
        [
            'key' => 'CL',
            'name_ar' => 'تشيلي ',
            'name_native' => 'Chile',
        ],
        [
            'key' => 'TZ',
            'name_ar' => 'تنزانيا ',
            'name_native' => 'Tanzania',
        ],
        [
            'key' => 'TG',
            'name_ar' => 'توغو ',
            'name_native' => 'Togo',
        ],
        [
            'key' => 'TV',
            'name_ar' => 'توفالو ',
            'name_native' => 'Tuvalu',
        ],
        [
            'key' => 'TK',
            'name_ar' => 'توكيلو ',
            'name_native' => 'Tokelau',
        ],
        [
            'key' => 'TN',
            'name_ar' => 'تونس ',
            'name_native' => 'Tunisia',
        ],
        [
            'key' => 'TO',
            'name_ar' => 'تونغا ',
            'name_native' => 'Tonga',
        ],
        [
            'key' => 'TL',
            'name_ar' => 'تيمور - ليشتي ',
            'name_native' => 'Timor-Leste',
        ],
        [
            'key' => 'JM',
            'name_ar' => 'جامايكا ',
            'name_native' => 'Jamaica',
        ],
        [
            'key' => 'GI',
            'name_ar' => 'جبل طارق ',
            'name_native' => 'Gibraltar',
        ],
        [
            'key' => 'AX',
            'name_ar' => 'جزر آلاند ',
            'name_native' => 'Åland',
        ],
        [
            'key' => 'BS',
            'name_ar' => 'جزر البهاما ',
            'name_native' => 'Bahamas',
        ],
        [
            'key' => 'KM',
            'name_ar' => 'جزر القمر     ',
        ],
        [
            'key' => 'IC',
            'name_ar' => 'جزر الكناري ',
            'name_native' => 'Canarias',
        ],
        [
            'key' => 'MQ',
            'name_ar' => 'جزر المارتينيك ',
            'name_native' => 'Martinique',
        ],
        [
            'key' => 'MV',
            'name_ar' => 'جزر المالديف ',
            'name_native' => 'Maldives',
        ],
        [
            'key' => 'UM',
            'name_ar' => 'جزر الولايات المتحدة النائية ',
            'name_native' => 'U.S. Outlying Islands',
        ],
        [
            'key' => 'PN',
            'name_ar' => 'جزر بيتكيرن ',
            'name_native' => 'Pitcairn Islands',
        ],
        [
            'key' => 'TC',
            'name_ar' => 'جزر توركس وكايكوس ',
            'name_native' => 'Turks & Caicos Islands',
        ],
        [
            'key' => 'SB',
            'name_ar' => 'جزر سليمان ',
            'name_native' => 'Solomon Islands',
        ],
        [
            'key' => 'FO',
            'name_ar' => 'جزر فارو ',
            'name_native' => 'Føroyar',
        ],
        [
            'key' => 'FK',
            'name_ar' => 'جزر فوكلاند - جزر مالفيناس ',
            'name_native' => 'Falkland Islands Islas Malvinas',
        ],
        [
            'key' => 'VG',
            'name_ar' => 'جزر فيرجن البريطانية ',
            'name_native' => 'British Virgin Islands',
        ],
        [
            'key' => 'VI',
            'name_ar' => 'جزر فيرجن التابعة للولايات المتحدة ',
            'name_native' => 'U.S. Virgin Islands',
        ],
        [
            'key' => 'KY',
            'name_ar' => 'جزر كايمان ',
            'name_native' => 'Cayman Islands',
        ],
        [
            'key' => 'CK',
            'name_ar' => 'جزر كوك ',
            'name_native' => 'Cook Islands',
        ],
        [
            'key' => 'CC',
            'name_ar' => 'جزر كوكوس ',
            'name_native' => 'كيلينغ Kepulauan Cocos Keeling',
        ],
        [
            'key' => 'MH',
            'name_ar' => 'جزر مارشال ',
            'name_native' => 'Marshall Islands',
        ],
        [
            'key' => 'MP',
            'name_ar' => 'جزر ماريانا الشمالية ',
            'name_native' => 'Northern Mariana Islands',
        ],
        [
            'key' => 'WF',
            'name_ar' => 'جزر والس وفوتونا ',
            'name_native' => 'Wallis & Futuna',
        ],
        [
            'key' => 'AC',
            'name_ar' => 'جزيرة أسينشيون ',
            'name_native' => 'Ascension Island',
        ],
        [
            'key' => 'BV',
            'name_ar' => 'جزيرة بوفيه ',
            'name_native' => 'Bouvet Island',
        ],
        [
            'key' => 'CX',
            'name_ar' => 'جزيرة كريسماس ',
            'name_native' => 'Christmas Island',
        ],
        [
            'key' => 'CP',
            'name_ar' => 'جزيرة كليبيرتون ',
            'name_native' => 'Clipperton Island',
        ],
        [
            'key' => 'IM',
            'name_ar' => 'جزيرة مان ',
            'name_native' => 'Isle of Man',
        ],
        [
            'key' => 'NF',
            'name_ar' => 'جزيرة نورفولك ',
            'name_native' => 'Norfolk Island',
        ],
        [
            'key' => 'HM',
            'name_ar' => 'جزيرة هيرد وجزر ماكدونالد ',
            'name_native' => 'Heard & McDonald Islands',
        ],
        [
            'key' => 'CF',
            'name_ar' => 'جمهورية أفريقيا الوسطى ',
            'name_native' => 'République centrafricaine',
        ],
        [
            'key' => 'DO',
            'name_ar' => 'جمهورية الدومينيكان ',
            'name_native' => 'República Dominicana',
        ],
        [
            'key' => 'ZA',
            'name_ar' => 'جنوب أفريقيا ',
            'name_native' => 'South Africa',
        ],
        [
            'key' => 'SS',
            'name_ar' => 'جنوب السودان       ',
        ],
        [
            'key' => 'GE',
            'name_ar' => 'جورجيا ',
            'name_native' => 'საქართველო',
        ],
        [
            'key' => 'GS',
            'name_ar' => 'جورجيا الجنوبية وجزر ساندويتش الجنوبية ',
            'name_native' => 'South Georgia & South Sandwich Islands',
        ],
        [
            'key' => 'DJ',
            'name_ar' => 'جيبوتي ',
            'name_native' => 'Djibouti',
        ],
        [
            'key' => 'JE',
            'name_ar' => 'جيرسي ',
            'name_native' => 'Jersey',
        ],
        [
            'key' => 'DM',
            'name_ar' => 'دومينيكا ',
            'name_native' => 'Dominica',
        ],
        [
            'key' => 'DG',
            'name_ar' => 'دييغو غارسيا ',
            'name_native' => 'Diego Garcia',
        ],
        [
            'key' => 'RW',
            'name_ar' => 'رواندا ',
            'name_native' => 'U Rwanda',
        ],
        [
            'key' => 'RU',
            'name_ar' => 'روسيا ',
            'name_native' => 'Россия',
        ],
        [
            'key' => 'RO',
            'name_ar' => 'رومانيا ',
            'name_native' => 'România',
        ],
        [
            'key' => 'RE',
            'name_ar' => 'روينيون ',
            'name_native' => 'La Réunion',
        ],
        [
            'key' => 'ZM',
            'name_ar' => 'زامبيا ',
            'name_native' => 'Zambia',
        ],
        [
            'key' => 'ZW',
            'name_ar' => 'زيمبابوي ',
            'name_native' => 'Zimbabwe',
        ],
        [
            'key' => 'CI',
            'name_ar' => 'ساحل العاج ',
            'name_native' => 'Côte d’Ivoire',
        ],
        [
            'key' => 'WS',
            'name_ar' => 'ساموا ',
            'name_native' => 'Samoa',
        ],
        [
            'key' => 'AS',
            'name_ar' => 'ساموا الأمريكية ',
            'name_native' => 'American Samoa',
        ],
        [
            'key' => 'BL',
            'name_ar' => 'سان بارتليمي ',
            'name_native' => 'Saint-Barthélemy',
        ],
        [
            'key' => 'PM',
            'name_ar' => 'سان بيير ومكويلون ',
            'name_native' => 'Saint-Pierre-et-Miquelon',
        ],
        [
            'key' => 'VC',
            'name_ar' => 'سانت فنسنت وجزر غرينادين ',
            'name_native' => 'St. Vincent & Grenadines',
        ],
        [
            'key' => 'KN',
            'name_ar' => 'سانت كيتس ونيفيس ',
            'name_native' => 'St. Kitts & Nevis',
        ],
        [
            'key' => 'LC',
            'name_ar' => 'سانت لوسيا ',
            'name_native' => 'St. Lucia',
        ],
        [
            'key' => 'SX',
            'name_ar' => 'سانت مارتن ',
            'name_native' => 'Sint Maarten',
        ],
        [
            'key' => 'SH',
            'name_ar' => 'سانت هيلينا ',
            'name_native' => 'St. Helena',
        ],
        [
            'key' => 'MF',
            'name_ar' => 'سان مارتن ',
            'name_native' => 'Saint-Martin',
        ],
        [
            'key' => 'SM',
            'name_ar' => 'سان مارينو ',
            'name_native' => 'San Marino',
        ],
        [
            'key' => 'ST',
            'name_ar' => 'ساو تومي وبرينسيبي ',
            'name_native' => 'São Tomé e Príncipe',
        ],
        [
            'key' => 'LK',
            'name_ar' => 'سريلانكا ',
            'name_native' => 'ශ්‍රී ලංකාව',
        ],
        [
            'key' => 'SJ',
            'name_ar' => 'سفالبارد وجان ماين ',
            'name_native' => 'Svalbard og Jan Mayen',
        ],
        [
            'key' => 'SK',
            'name_ar' => 'سلوفاكيا ',
            'name_native' => 'Slovensko',
        ],
        [
            'key' => 'SI',
            'name_ar' => 'سلوفينيا ',
            'name_native' => 'Slovenija',
        ],
        [
            'key' => 'SG',
            'name_ar' => 'سنغافورة ',
            'name_native' => 'Singapore',
        ],
        [
            'key' => 'SY',
            'name_ar' => 'سوريا     ',
        ],
        [
            'key' => 'SR',
            'name_ar' => 'سورينام ',
            'name_native' => 'Suriname',
        ],
        [
            'key' => 'CH',
            'name_ar' => 'سويسرا ',
            'name_native' => 'Schweiz',
        ],
        [
            'key' => 'SL',
            'name_ar' => 'سيراليون ',
            'name_native' => 'Sierra Leone',
        ],
        [
            'key' => 'SC',
            'name_ar' => 'سيشل ',
            'name_native' => 'Seychelles',
        ],
        [
            'key' => 'EA',
            'name_ar' => 'سيوتا وميليلا ',
            'name_native' => 'Ceuta y Melilla',
        ],
        [
            'key' => 'RS',
            'name_ar' => 'صربيا ',
            'name_native' => 'Србија',
        ],
        [
            'key' => 'TJ',
            'name_ar' => 'طاجيكستان ',
            'name_native' => 'Тоҷикистон',
        ],
        [
            'key' => 'OM',
            'name_ar' => 'عُمان     ',
        ],
        [
            'key' => 'GM',
            'name_ar' => 'غامبيا ',
            'name_native' => 'Gambia',
        ],
        [
            'key' => 'GH',
            'name_ar' => 'غانا ',
            'name_native' => 'Gaana',
        ],
        [
            'key' => 'GD',
            'name_ar' => 'غرينادا ',
            'name_native' => 'Grenada',
        ],
        [
            'key' => 'GL',
            'name_ar' => 'غرينلاند ',
            'name_native' => 'Kalaallit Nunaat',
        ],
        [
            'key' => 'GT',
            'name_ar' => 'غواتيمالا ',
            'name_native' => 'Guatemala',
        ],
        [
            'key' => 'GP',
            'name_ar' => 'غوادلوب ',
            'name_native' => 'Guadeloupe',
        ],
        [
            'key' => 'GU',
            'name_ar' => 'غوام ',
            'name_native' => 'Guam',
        ],
        [
            'key' => 'GF',
            'name_ar' => 'غويانا الفرنسية ',
            'name_native' => 'Guyane française',
        ],
        [
            'key' => 'GY',
            'name_ar' => 'غيانا ',
            'name_native' => 'Guyana',
        ],
        [
            'key' => 'GG',
            'name_ar' => 'غيرنزي ',
            'name_native' => 'Guernsey',
        ],
        [
            'key' => 'GN',
            'name_ar' => 'غينيا ',
            'name_native' => 'Guinée',
        ],
        [
            'key' => 'GQ',
            'name_ar' => 'غينيا الاستوائية ',
            'name_native' => 'Guinea Ecuatorial',
        ],
        [
            'key' => 'GW',
            'name_ar' => 'غينيا بيساو ',
            'name_native' => 'Guiné-Bissau',
        ],
        [
            'key' => 'VU',
            'name_ar' => 'فانواتو ',
            'name_native' => 'Vanuatu',
        ],
        [
            'key' => 'FR',
            'name_ar' => 'فرنسا ',
            'name_native' => 'France',
        ],
        [
            'key' => 'PS',
            'name_ar' => 'فلسطين      ',
        ],
        [
            'key' => 'VE',
            'name_ar' => 'فنزويلا ',
            'name_native' => 'Venezuela',
        ],
        [
            'key' => 'FI',
            'name_ar' => 'فنلندا ',
            'name_native' => 'Suomi',
        ],
        [
            'key' => 'VN',
            'name_ar' => 'فيتنام ',
            'name_native' => 'Việt Nam',
        ],
        [
            'key' => 'FJ',
            'name_ar' => 'فيجي ',
            'name_native' => 'Fiji',
        ],
        [
            'key' => 'CY',
            'name_ar' => 'قبرص ',
            'name_native' => 'Κύπρος',
        ],
        [
            'key' => 'QA',
            'name_ar' => 'قطر   ',
        ],
        [
            'key' => 'KG',
            'name_ar' => 'قيرغيزستان ',
            'name_native' => 'Кыргызстан',
        ],
        [
            'key' => 'KZ',
            'name_ar' => 'كازاخستان ',
            'name_native' => 'Казахстан',
        ],
        [
            'key' => 'NC',
            'name_ar' => 'كاليدونيا الجديدة ',
            'name_native' => 'Nouvelle-Calédonie',
        ],
        [
            'key' => 'HR',
            'name_ar' => 'كرواتيا ',
            'name_native' => 'Hrvatska',
        ],
        [
            'key' => 'KH',
            'name_ar' => 'كمبوديا ',
            'name_native' => 'កម្ពុជា',
        ],
        [
            'key' => 'CA',
            'name_ar' => 'كندا ',
            'name_native' => 'Canada',
        ],
        [
            'key' => 'CU',
            'name_ar' => 'كوبا ',
            'name_native' => 'Cuba',
        ],
        [
            'key' => 'CW',
            'name_ar' => 'كوراساو ',
            'name_native' => 'Curaçao',
        ],
        [
            'key' => 'KR',
            'name_ar' => 'كوريا الجنوبية ',
            'name_native' => '대한민국',
        ],
        [
            'key' => 'KP',
            'name_ar' => 'كوريا الشمالية ',
            'name_native' => '북한',
        ],
        [
            'key' => 'CR',
            'name_ar' => 'كوستاريكا ',
            'name_native' => 'Costa Rica',
        ],
        [
            'key' => 'XK',
            'name_ar' => 'كوسوفو ',
            'name_native' => 'Kosovë',
        ],
        [
            'key' => 'CO',
            'name_ar' => 'كولومبيا ',
            'name_native' => 'Colombia',
        ],
        [
            'key' => 'KI',
            'name_ar' => 'كيريباتي ',
            'name_native' => 'Kiribati',
        ],
        [
            'key' => 'KE',
            'name_ar' => 'كينيا ',
            'name_native' => 'Kenya',
        ],
        [
            'key' => 'LV',
            'name_ar' => 'لاتفيا ',
            'name_native' => 'Latvija',
        ],
        [
            'key' => 'LA',
            'name_ar' => 'لاوس ',
            'name_native' => 'ລາວ',
        ],
        [
            'key' => 'LB',
            'name_ar' => 'لبنان     ',
        ],
        [
            'key' => 'LU',
            'name_ar' => 'لوكسمبورغ ',
            'name_native' => 'Luxembourg',
        ],
        [
            'key' => 'LY',
            'name_ar' => 'ليبيا     ',
        ],
        [
            'key' => 'LR',
            'name_ar' => 'ليبيريا ',
            'name_native' => 'Liberia',
        ],
        [
            'key' => 'LT',
            'name_ar' => 'ليتوانيا ',
            'name_native' => 'Lietuva',
        ],
        [
            'key' => 'LI',
            'name_ar' => 'ليختنشتاين ',
            'name_native' => 'Liechtenstein',
        ],
        [
            'key' => 'LS',
            'name_ar' => 'ليسوتو ',
            'name_native' => 'Lesotho',
        ],
        [
            'key' => 'MT',
            'name_ar' => 'مالطا ',
            'name_native' => 'Malta',
        ],
        [
            'key' => 'ML',
            'name_ar' => 'مالي ',
            'name_native' => 'Mali',
        ],
        [
            'key' => 'MY',
            'name_ar' => 'ماليزيا ',
            'name_native' => 'Malaysia',
        ],
        [
            'key' => 'YT',
            'name_ar' => 'مايوت ',
            'name_native' => 'Mayotte',
        ],
        [
            'key' => 'MG',
            'name_ar' => 'مدغشقر ',
            'name_native' => 'Madagasikara',
        ],
        [
            'key' => 'EG',
            'name_ar' => 'مصر   ',
        ],
        [
            'key' => 'MK',
            'name_ar' => 'مقدونيا الشمالية ',
            'name_native' => 'Северна Македонија',
        ],
        [
            'key' => 'MO',
            'name_ar' => 'مكاو ',
            'name_native' => '澳門',
        ],
        [
            'key' => 'MW',
            'name_ar' => 'ملاوي ',
            'name_native' => 'Malawi',
        ],
        [
            'key' => 'MN',
            'name_ar' => 'منغوليا ',
            'name_native' => 'Монгол',
        ],
        [
            'key' => 'MR',
            'name_ar' => 'موريتانيا         ',
        ],
        [
            'key' => 'MU',
            'name_ar' => 'موريشيوس ',
            'name_native' => 'Moris',
        ],
        [
            'key' => 'MZ',
            'name_ar' => 'موزمبيق ',
            'name_native' => 'Moçambique',
        ],
        [
            'key' => 'MD',
            'name_ar' => 'مولدوفا ',
            'name_native' => 'Republica Moldova',
        ],
        [
            'key' => 'MC',
            'name_ar' => 'موناكو ',
            'name_native' => 'Monaco',
        ],
        [
            'key' => 'MS',
            'name_ar' => 'مونتسرات ',
            'name_native' => 'Montserrat',
        ],
        [
            'key' => 'MM',
            'name_ar' => 'ميانمار ',
            'name_native' => 'بورما မြန်မာ',
        ],
        [
            'key' => 'FM',
            'name_ar' => 'ميكرونيزيا ',
            'name_native' => 'Micronesia',
        ],
        [
            'key' => 'NA',
            'name_ar' => 'ناميبيا ',
            'name_native' => 'Namibië',
        ],
        [
            'key' => 'NR',
            'name_ar' => 'ناورو ',
            'name_native' => 'Nauru',
        ],
        [
            'key' => 'NP',
            'name_ar' => 'نيبال ',
            'name_native' => 'नेपाल',
        ],
        [
            'key' => 'NG',
            'name_ar' => 'نيجيريا ',
            'name_native' => 'Nigeria',
        ],
        [
            'key' => 'NI',
            'name_ar' => 'نيكاراغوا ',
            'name_native' => 'Nicaragua',
        ],
        [
            'key' => 'NZ',
            'name_ar' => 'نيوزيلندا ',
            'name_native' => 'New Zealand',
        ],
        [
            'key' => 'NU',
            'name_ar' => 'نيوي ',
            'name_native' => 'Niue',
        ],
        [
            'key' => 'HT',
            'name_ar' => 'هايتي ',
            'name_native' => 'Haiti',
        ],
        [
            'key' => 'HN',
            'name_ar' => 'هندوراس ',
            'name_native' => 'Honduras',
        ],
        [
            'key' => 'HU',
            'name_ar' => 'هنغاريا ',
            'name_native' => 'Magyarország',
        ],
        [
            'key' => 'NL',
            'name_ar' => 'هولندا ',
            'name_native' => 'Nederland',
        ],
        [
            'key' => 'BQ',
            'name_ar' => 'هولندا الكاريبية ',
            'name_native' => 'Caribbean Netherlands',
        ],
        [
            'key' => 'HK',
            'name_ar' => 'هونغ كونغ ',
            'name_native' => '香港',
        ],
    ];

    public const COUNTRIES_ENGLISH = [
        ['name_en' => 'Afghanistan'],
        ['name_en' => 'Åland Islands'],
        ['name_en' => 'Albania'],
        ['name_en' => 'Algeria'],
        ['name_en' => 'American Samoa'],
        ['name_en' => 'Andorra'],
        ['name_en' => 'Angola'],
        ['name_en' => 'Anguilla'],
        ['name_en' => 'Antarctica'],
        ['name_en' => 'Antigua & Barbuda'],
        ['name_en' => 'Argentina'],
        ['name_en' => 'Armenia'],
        ['name_en' => 'Aruba'],
        ['name_en' => 'Ascension Island'],
        ['name_en' => 'Australia'],
        ['name_en' => 'Austria'],
        ['name_en' => 'Azerbaijan'],
        ['name_en' => 'Bahamas'],
        ['name_en' => 'Bahrain'],
        ['name_en' => 'Bangladesh'],
        ['name_en' => 'Barbados'],
        ['name_en' => 'Belarus'],
        ['name_en' => 'Belgium'],
        ['name_en' => 'Belize'],
        ['name_en' => 'Benin'],
        ['name_en' => 'Bermuda'],
        ['name_en' => 'Bhutan'],
        ['name_en' => 'Bolivia'],
        ['name_en' => 'Bosnia & Herzegovina'],
        ['name_en' => 'Botswana'],
        ['name_en' => 'Bouvet Island'],
        ['name_en' => 'Brazil'],
        ['name_en' => 'British Indian Ocean Territory'],
        ['name_en' => 'British Virgin Islands'],
        ['name_en' => 'Brunei'],
        ['name_en' => 'Bulgaria'],
        ['name_en' => 'Burkina Faso'],
        ['name_en' => 'Burundi'],
        ['name_en' => 'Cambodia'],
        ['name_en' => 'Cameroon'],
        ['name_en' => 'Canada'],
        ['name_en' => 'Canary Islands'],
        ['name_en' => 'Cape Verde'],
        ['name_en' => 'Caribbean Netherlands'],
        ['name_en' => 'Cayman Islands'],
        ['name_en' => 'Central African Republic'],
        ['name_en' => 'Ceuta & Melilla'],
        ['name_en' => 'Chad'],
        ['name_en' => 'Chile'],
        ['name_en' => 'China'],
        ['name_en' => 'Christmas Island'],
        ['name_en' => 'Clipperton Island'],
        ['name_en' => 'Cocos'],
        ['name_en' => 'Colombia'],
        ['name_en' => 'Comoros'],
        ['name_en' => 'Congo - Brazzaville'],
        ['name_en' => 'Congo - Kinshasa'],
        ['name_en' => 'Cook Islands'],
        ['name_en' => 'Costa Rica'],
        ['name_en' => 'Côte d’Ivoire'],
        ['name_en' => 'Croatia'],
        ['name_en' => 'Cuba'],
        ['name_en' => 'Curaçao'],
        ['name_en' => 'Cyprus'],
        ['name_en' => 'Czechia'],
        ['name_en' => 'Denmark'],
        ['name_en' => 'Diego Garcia'],
        ['name_en' => 'Djibouti'],
        ['name_en' => 'Dominica'],
        ['name_en' => 'Dominican Republic'],
        ['name_en' => 'Ecuador'],
        ['name_en' => 'Egypt'],
        ['name_en' => 'El Salvador'],
        ['name_en' => 'Equatorial Guinea'],
        ['name_en' => 'Eritrea'],
        ['name_en' => 'Estonia'],
        ['name_en' => 'Eswatini'],
        ['name_en' => 'Ethiopia'],
        ['name_en' => 'Falkland Islands'],
        ['name_en' => 'Faroe Islands'],
        ['name_en' => 'Fiji'],
        ['name_en' => 'Finland'],
        ['name_en' => 'France'],
        ['name_en' => 'French Guiana'],
        ['name_en' => 'French Polynesia'],
        ['name_en' => 'French Southern Territories'],
        ['name_en' => 'Gabon'],
        ['name_en' => 'Gambia'],
        ['name_en' => 'Georgia'],
        ['name_en' => 'Germany'],
        ['name_en' => 'Ghana'],
        ['name_en' => 'Gibraltar'],
        ['name_en' => 'Greece'],
        ['name_en' => 'Greenland'],
        ['name_en' => 'Grenada'],
        ['name_en' => 'Guadeloupe'],
        ['name_en' => 'Guam'],
        ['name_en' => 'Guatemala'],
        ['name_en' => 'Guernsey'],
        ['name_en' => 'Guinea'],
        ['name_en' => 'Guinea-Bissau'],
        ['name_en' => 'Guyana'],
        ['name_en' => 'Haiti'],
        ['name_en' => 'Heard & McDonald Islands'],
        ['name_en' => 'Honduras'],
        ['name_en' => 'Hong Kong'],
        ['name_en' => 'Hungary'],
        ['name_en' => 'Iceland'],
        ['name_en' => 'India'],
        ['name_en' => 'Indonesia'],
        ['name_en' => 'Iran'],
        ['name_en' => 'Iraq'],
        ['name_en' => 'Ireland'],
        ['name_en' => 'Isle of Man'],
        ['name_en' => 'Israel'],
        ['name_en' => 'Italy'],
        ['name_en' => 'Jamaica'],
        ['name_en' => 'Japan'],
        ['name_en' => 'Jersey'],
        ['name_en' => 'Jordan'],
        ['name_en' => 'Kazakhstan'],
        ['name_en' => 'Kenya'],
        ['name_en' => 'Kiribati'],
        ['name_en' => 'Kosovo'],
        ['name_en' => 'Kuwait'],
        ['name_en' => 'Kyrgyzstan'],
        ['name_en' => 'Laos'],
        ['name_en' => 'Latvia'],
        ['name_en' => 'Lebanon'],
        ['name_en' => 'Lesotho'],
        ['name_en' => 'Liberia'],
        ['name_en' => 'Libya'],
        ['name_en' => 'Liechtenstein'],
        ['name_en' => 'Lithuania'],
        ['name_en' => 'Luxembourg'],
        ['name_en' => 'Macao'],
        ['name_en' => 'Madagascar'],
        ['name_en' => 'Malawi'],
        ['name_en' => 'Malaysia'],
        ['name_en' => 'Maldives'],
        ['name_en' => 'Mali'],
        ['name_en' => 'Malta'],
        ['name_en' => 'Marshall Islands'],
        ['name_en' => 'Martinique'],
        ['name_en' => 'Mauritania'],
        ['name_en' => 'Mauritius'],
        ['name_en' => 'Mayotte'],
        ['name_en' => 'Mexico'],
        ['name_en' => 'Micronesia'],
        ['name_en' => 'Moldova'],
        ['name_en' => 'Monaco'],
        ['name_en' => 'Mongolia'],
        ['name_en' => 'Montenegro'],
        ['name_en' => 'Montserrat'],
        ['name_en' => 'Morocco'],
        ['name_en' => 'Mozambique'],
        ['name_en' => 'Myanmar'],
        ['name_en' => 'Namibia'],
        ['name_en' => 'Nauru'],
        ['name_en' => 'Nepal'],
        ['name_en' => 'Netherlands'],
        ['name_en' => 'New Caledonia'],
        ['name_en' => 'New Zealand'],
        ['name_en' => 'Nicaragua'],
        ['name_en' => 'Niger'],
        ['name_en' => 'Nigeria'],
        ['name_en' => 'Niue'],
        ['name_en' => 'Norfolk Island'],
        ['name_en' => 'Northern Mariana Islands'],
        ['name_en' => 'North Korea'],
        ['name_en' => 'North Macedonia'],
        ['name_en' => 'Norway'],
        ['name_en' => 'Oman'],
        ['name_en' => 'Pakistan'],
        ['name_en' => 'Palau'],
        ['name_en' => 'Palestine'],
        ['name_en' => 'Panama'],
        ['name_en' => 'Papua New Guinea'],
        ['name_en' => 'Paraguay'],
        ['name_en' => 'Peru'],
        ['name_en' => 'Philippines'],
        ['name_en' => 'Pitcairn Islands'],
        ['name_en' => 'Poland'],
        ['name_en' => 'Portugal'],
        ['name_en' => 'Puerto Rico'],
        ['name_en' => 'Qatar'],
        ['name_en' => 'Réunion'],
        ['name_en' => 'Romania'],
        ['name_en' => 'Russia'],
        ['name_en' => 'Rwanda'],
        ['name_en' => 'Samoa'],
        ['name_en' => 'San Marino'],
        ['name_en' => 'São Tomé & Príncipe'],
        ['name_en' => 'Saudi Arabia'],
        ['name_en' => 'Senegal'],
        ['name_en' => 'Serbia'],
        ['name_en' => 'Seychelles'],
        ['name_en' => 'Sierra Leone'],
        ['name_en' => 'Singapore'],
        ['name_en' => 'Sint Maarten'],
        ['name_en' => 'Slovakia'],
        ['name_en' => 'Slovenia'],
        ['name_en' => 'Solomon Islands'],
        ['name_en' => 'Somalia'],
        ['name_en' => 'South Africa'],
        ['name_en' => 'South Georgia & South Sandwich Islands'],
        ['name_en' => 'South Korea'],
        ['name_en' => 'South Sudan'],
        ['name_en' => 'Spain'],
        ['name_en' => 'Sri Lanka'],
        ['name_en' => 'St Barthélemy'],
        ['name_en' => 'St Helena'],
        ['name_en' => 'St Kitts & Nevis'],
        ['name_en' => 'St Lucia'],
        ['name_en' => 'St Martin'],
        ['name_en' => 'St Pierre & Miquelon'],
        ['name_en' => 'St Vincent & the Grenadines'],
        ['name_en' => 'Sudan'],
        ['name_en' => 'Suriname'],
        ['name_en' => 'Svalbard & Jan Mayen'],
        ['name_en' => 'Sweden'],
        ['name_en' => 'Switzerland'],
        ['name_en' => 'Syria'],
        ['name_en' => 'Taiwan'],
        ['name_en' => 'Tajikistan'],
        ['name_en' => 'Tanzania'],
        ['name_en' => 'Thailand'],
        ['name_en' => 'Timor-Leste'],
        ['name_en' => 'Togo'],
        ['name_en' => 'Tokelau'],
        ['name_en' => 'Tonga'],
        ['name_en' => 'Trinidad & Tobago'],
        ['name_en' => 'Tristan da Cunha'],
        ['name_en' => 'Tunisia'],
        ['name_en' => 'Turkey'],
        ['name_en' => 'Turkmenistan'],
        ['name_en' => 'Turks & Caicos Islands'],
        ['name_en' => 'Tuvalu'],
        ['name_en' => 'Uganda'],
        ['name_en' => 'Ukraine'],
        ['name_en' => 'United Arab Emirates'],
        ['name_en' => 'United Kingdom'],
        ['name_en' => 'United States'],
        ['name_en' => 'Uruguay'],
        ['name_en' => 'US Outlying Islands'],
        ['name_en' => 'US Virgin Islands'],
        ['name_en' => 'Uzbekistan'],
        ['name_en' => 'Vanuatu'],
        ['name_en' => 'Vatican City'],
        ['name_en' => 'Venezuela'],
        ['name_en' => 'Vietnam'],
        ['name_en' => 'Wallis & Futuna'],
        ['name_en' => 'Western Sahara'],
        ['name_en' => 'Yemen'],
        ['name_en' => 'Zambia'],
        ['name_en' => 'Zimbabwe'],
    ];

    public static function getProcessedCountries(): array
    {
        $arr = [];

        foreach (self::GOOGLE_COUNTRIES as $country) {
            $arr[] = [
                'code' => trim($country['key']),
                'name_ar' => trim($country['name_ar']),
                'name_native' => isset($country['name_native']) ? trim($country['name_native']) : trim($country['name_ar']),
            ];
        }

        return $arr;
    }

    public static function getCountryKeys(): array
    {
        return array_column(self::getProcessedCountries(), 'code');
    }
}
